### PR TITLE
Add test generator for examples in examples/ directory

### PR DESCRIPTION
**Pull request by travs**
Also added a couple dependencies I needed to get the examples working to INSTALL.rst.

Let's see if the tests pass on Travis (CI)...

### CODE REVIEW

**Comment by MichaelCurrie** [comment]
It looks like the build tests are failing simply because they can't access the example files, since the Travis build machine does not contain a copy of the Google Drive example folder.

@slarson discusses a solution to this, via public links, here: https://github.com/openworm/movement_validation/issues/107.  What do you think, @travs?

**Comment by travs** [comment]
@michaelcurrie
Oh right, I should have realized this would fail. Yeah the solution in #107 sounds reasonable.
I'll see if gdrive can do this to avoid having to mirror to dropbox, but that's a catchall if gdrive does not support it.

**Comment by travs** [comment]
Ok, it appears that we **can** access files with a permanent URL directly from google drive, so that's a plus.

Knowing this, I tried to make the `EXAMPLE_DATA_PATH` variable in `user_config.py` accept a URL using different means (wrapping, etc.) but I couldn't get it to work ([here's an open SO question](http://stackoverflow.com/questions/30429817/wrap-url-as-filesystem-path/30429884#30429884) that reaches a little more detail).

Now the options seem to be either:
1. Modify the functions expecting a filesystem path ([example](https://github.com/openworm/movement_validation/blob/master/movement_validation/NormalizedWorm.py#L94)) to also accept a URL, or:
2. Download the `example_data` directory from google drive on every TravisCI build (1.1 GB zipped, currently)

Option 1 seems to be more difficult, but ultimately builds faster than cloning the `example_data` directory at every build (Option 2), especially if that directory grows. 

There are probably better solutions than these two; any suggestions?

@MichaelCurrie

**Comment by travs** [comment]
One thing I just thought of is that a lot of the files in `example_data` may not be used for the *tested* examples, so we could just download the files that are needed for those [enumerated examples](https://github.com/travs/movement_validation/commit/0b094d17878679f604df63ba9ad9bcaac0b4011f#diff-713a07b0b4e3c7a57a5f93f9f8ffe8d4R41). 

The problem, however, is that there is currently no programmatic way to know which `example_data` files are required by a given example script.

**Comment by JimHokanson** [comment]
What's the status on this? How can I help?

**Comment by MichaelCurrie** [comment]
I believe the problem is we need to find a way to download from Google Drive rather than assume the example files are on the local drive.  This shouldn't be too difficult.

**Comment by slarson** [comment]
Place to start?

https://pypi.python.org/pypi/PyDrive

**Comment by JimHokanson** [comment]
Our example files aren't that large or numerous right now. I've updated the Travis yml file  to handle our basic "Validate Features" code.

Looking at Travis' code, the example code should now work but I think the pathing isn't quite right.

A design decision we need to make is how we are going to organize tests. I like what Travis has started here but we should really get some rules laid out. I added a 2nd test that runs Validate Features ...

**Comment by JimHokanson** [comment]
I merged the pull request to keep Travis' contributions. There were some problems with the examples unit tests which were in part based on using Anaconda in travis.ci. Thanks for getting this going Travis!

**Pull request merged**
