### PR TITLE
Improve Eccentricity calculation

### PR DESCRIPTION
**Pull request by ver228**

### CODE REVIEW

**Comment by MichaelCurrie** [comment]
Look like this is failing the Travis CI tests, partly because we need to add code to install cv2 on the Travis build machine in the [`.travis.yml` file](https://github.com/openworm/movement_validation/blob/master/.travis.yml).  Also it appears there might be some other errors as it's failing saying the `utils` module cannot be imported.

**Comment by JimHokanson** [comment]
Going to test rebuilding

**Comment by JimHokanson** [comment]
Ok, it looks like closing and opening retriggers the build. Let's fix the Travis file

**Comment by JimHokanson** [comment]
The comment in this post might help:
http://seabre.github.io/blog/2014/03/09/setting-up-travis-ci-for-opencv-and-midje/

**Comment by JimHokanson** [comment]
Not sure if the pull request is really going through Travis again, closing and starting a new one

**Comment by JimHokanson** [comment]
@ver228 Moved this to #137 due to some silliness on my end

**Pull request closed without merging**
